commit_message: "%language% (%file_name%.%file_extension%) [skip ci]"

files:
  - source: /Anytype/Resources/Strings/en.lproj/*
    translation: /Anytype/Resources/Strings/%osx_locale%.lproj/%original_file_name%
