name: License Checks
runs:
  using: "composite"
  steps:
    - name: Setup license repository
      uses: actions/checkout@master
      with:
        repository: anytypeio/open
        ref: refs/heads/main
        path: ./build/open

    - name: Test license checks
      shell: bash
      run: bundle exec fastlane check_lisence