name: Update git config
runs:
  steps:
    - name: Update git config
        run: |
          git config --global url.ssh://git@github.com/.insteadOf https://github.com/
          git config --global user.name "William Blake"
          git config --global user.email "iosteam@anytype.io"