name: Run tests on PR

on:
  pull_request:
    branches: [ "develop", "release" ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ${{ vars.RUNNER }}
    timeout-minutes: 35

    steps:
      - name: Install SSH key for access to repository
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_ACCESS_KEY }}
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update git config
        uses: ./.github/actions/update-git-config

      - name: Prepare deps
        uses: ./.github/actions/prepare-deps

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: '14.3'

      - name: Download Middleware
        run: ruby ./Scripts/middleware.rb --token ${{ secrets.ANYTYPE_MIDDLEWARE_ACCESS_TOKEN }}

      - name: License Checks
        uses: ./.github/actions/license-checks

      - name: Run unit tests
        run: bundle exec fastlane tests skip_notify:true
        env:
          SLACK_URL_BUILD_TESTS: ${{ secrets.SLACK_URL_BUILD_TESTS }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 900
          FASTLANE_XCODE_LIST_TIMEOUT: 900
