name: Anytype

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'     
        required: true
        default: 'release'

jobs:
  main:
    runs-on: macOS-11
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install SSH key for access to repository.
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_FASTLANE_COMMIT }}

      - name: Setup ruby
        uses: ruby/setup-ruby@v1.81.0
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Update git config
        run: |
          git config --global url.ssh://git@github.com/.insteadOf https://github.com/
          git config --global user.name "William Blake"
          git config --global user.email "iosteam@anytype.io"

      - uses: maxim-lobanov/setup-xcode@v1.3.0
        with:
          xcode-version: '13.0'

      - name: Download Middleware
        run: ruby ./Scripts/middleware-ci.rb --token ${{ secrets.ANYTYPE_MIDDLEWARE_ACCESS_TOKEN }}

      - name: Build and upload to Testflight
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          bundle exec fastlane release
        env:
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.SSH_KEY_FASTLANE_MATCH }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}

  wait_for_dSYM:
    needs: main
    runs-on: ubuntu-latest
    timeout-minutes: 67

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.inputs.branch }}
          
      - name: Setup ruby
        uses: ruby/setup-ruby@v1.81.0
        with:
            ruby-version: 2.7.2
            bundler-cache: true

      - name: Download dSYM
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          bundle exec download_release_symbols
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
  
  update_dSYM:
    needs: wait_for_dSYM
    runs-on: macOS-11
    timeout-minutes: 25

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.inputs.branch }}
          
      - name: Setup ruby
        uses: ruby/setup-ruby@v1.81.0
        with:
            ruby-version: 2.7.2
            bundler-cache: true

      - name: Update dev dSYMs
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          bundle exec fastlane update_release_symbols version:"lates"
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}          


