name: "build-test"
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'     
        required: false
        default: 'develop'

jobs:
  build: # make sure build/ci work properly
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run all
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install --production
    - uses: ./
      id: provisioning
      with:
        bundle-id: 'com.anytypeio.anytype'
        profile-type: 'IOS_APP_DEVELOPMENT'
        issuer-id: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
        api-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        api-private-key: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
    - run: |
        echo ${{ steps.provisioning.outputs.profiles }}
